name: test-nodejs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [master]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  test-nodejs:
    runs-on: ${{ matrix.os }}
    name: Test NodeJS ${{ matrix.node_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ['16', '18', '20']
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup NodeJS ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          # choose node.js version to use
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      # cache node_modules
      - name: Cache dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # install dependencies if the cache did not hit
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i

      # run test
      - name: Test module script
        run: npm run test
