name: test-nodejs

on:
  pull_request:
    branches: [main]
  # trigger deployment on every push to main branch
  push:
    paths:
      - '**'
      - '!LICENSE'
      - '!*.md'
      - '!.github/**'
      - '!.vscode/**'
      - '!docs/**'
  # trigger deployment manually
  workflow_dispatch:

jobs:
  test-nodejs:
    runs-on: ${{ matrix.os }}
    name: Test NodeJS ${{ matrix.node_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ['18', '20', '22']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        name: Setup Node.js ${{ matrix.node_version }}
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          # choose node.js version to use
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'
        run: npm ci

      # run test
      - name: Test module script
        run: npm run test
